pub struct WallpaperPreviewUi {
    pub(super) pipeline: wgpu::RenderPipeline,
    pub(super) bind_group_layout: wgpu::BindGroupLayout,
    pub(super) sampler: wgpu::Sampler,
    pub(super) texture: wgpu::Texture,
    pub(super) texture_view: wgpu::TextureView,
    pub(super) bind_group: wgpu::BindGroup,
    pub(super) tex_width: u32,
    pub(super) tex_height: u32,
    pub(super) vertex_buffer: wgpu::Buffer,
    pub(super) vertex_count: u32,
    pub(super) preview_pipeline: wgpu::RenderPipeline,
    pub(super) preview_source_texture: wgpu::Texture,
    pub(super) preview_blur_texture: wgpu::Texture,
    pub(super) preview_bind_group: wgpu::BindGroup,
    pub(super) preview_params_buffer: wgpu::Buffer,
    pub(super) preview_vertex_buffer: wgpu::Buffer,
    pub(super) preview_vertex_count: u32,
    pub(super) preview_source_ready: bool,
    pub(super) preview_blur_ready: bool,

    pub(super) visible: bool,
    pub(super) source_loading: bool,
    pub(super) blur_enabled: bool,
    pub(super) original_pixels: std::sync::Arc<Vec<u8>>,
    pub(super) original_width: u32,
    pub(super) original_height: u32,
    pub(super) blurred_pixels: Option<Vec<u8>>,
    pub(super) blurred_width: u32,
    pub(super) blurred_height: u32,
    pub(super) blur_rx: Option<std::sync::mpsc::Receiver<Result<(Vec<u8>, u32, u32), String>>>,
    pub(super) blur_loading: bool,
    pub(super) blur_mix: f32,
    pub(super) blur_anim_from: f32,
    pub(super) blur_anim_to: f32,
    pub(super) blur_anim_started_at: Option<std::time::Instant>,
    pub(super) blur_anim_duration: std::time::Duration,
    pub(super) preview_source_pixels: Vec<u8>,
    pub(super) preview_blur_pixels: Vec<u8>,
    pub(super) dim_amount: f32,
    pub(super) dim_dragging: bool,
    pub(super) editing_wallpaper_id: Option<u64>,
    pub(super) selected_source_path: Option<std::path::PathBuf>,

    pub(super) dialog_rect_px: [f32; 4],
    pub(super) toggle_rect_px: [f32; 4],
    pub(super) dim_rect_px: [f32; 4],
    pub(super) dim_track_x0_px: f32,
    pub(super) dim_track_x1_px: f32,
    pub(super) apply_rect_px: [f32; 4],
    pub(super) cancel_rect_px: [f32; 4],
    pub(super) last_surface_width: u32,
    pub(super) last_surface_height: u32,
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
pub(super) struct WallpaperPreviewParams {
    pub(super) values: [f32; 4],
}
